import { IBusiness } from '@/interfaces/business';

export const businesses: IBusiness[] = [
  {
    id: '1',
    name: 'مد وینتیج',
    websiteUrl: 'https://www.vintagefashionhub.com',
    instagram: '@vintagefashionhub',
    score: 4.8,
    category: 'fashion',
    description: 'فروش انواع لباس‌های وینتیج و خاص با بهترین کیفیت',
    address: 'خیابان مد، تهران',
    phone: '+98 912 345 6789',
    email: 'info@vintagefashionhub.com',
    tags: ['Vintage', 'Handmade', 'Unique'],
    reviewCount: 180,
    ratingDistribution: {
      1: 2,
      2: 4,
      3: 12,
      4: 50,
      5: 112,
    },
  },
  {
    id: '2',
    name: 'زیبایی طبیعی',
    websiteUrl: 'https://www.naturalbeautyco.com',
    instagram: '@naturalbeautyco',
    score: 4.9,
    category: 'beauty',
    description: 'محصولات مراقبت از پوست و زیبایی ارگانیک و طبیعی',
    address: 'خیابان بهداشت، شیراز',
    phone: '+98 935 678 9123',
    email: 'support@naturalbeautyco.com',
    tags: ['Organic', 'Skin Care', 'Vegan'],
    reviewCount: 210,
    ratingDistribution: {
      1: 1,
      2: 2,
      3: 10,
      4: 40,
      5: 157,
    },
  },
  {
    id: '3',
    name: 'هنر دست‌ساز نقره',
    websiteUrl: 'https://www.silverhandcrafts.com',
    instagram: '@silverhandcrafts',
    score: 4.7,
    category: 'handmade',
    description: 'جواهرات و محصولات هنری دست‌ساز با طراحی خاص',
    address: 'بازار هنر، اصفهان',
    phone: '+98 911 123 4567',
    email: 'contact@silverhandcrafts.com',
    tags: ['Jewelry', 'Handmade', 'Silver'],
    reviewCount: 95,
    ratingDistribution: {
      1: 3,
      2: 5,
      3: 15,
      4: 30,
      5: 42,
    },
  },
  {
    id: '4',
    name: 'کافه دسر شیرین',
    websiteUrl: 'https://www.sweetdessertcafe.com',
    instagram: '@sweetdessertcafe',
    score: 4.8,
    category: 'desserts',
    description: 'انواع دسرهای خوشمزه و کیک‌های سفارشی',
    address: 'خیابان طعم شیرین، تهران',
    phone: '+98 912 789 1234',
    email: 'orders@sweetdessertcafe.com',
    tags: ['Desserts', 'Cakes', 'Coffee'],
    reviewCount: 300,
    ratingDistribution: {
      1: 2,
      2: 5,
      3: 18,
      4: 65,
      5: 210,
    },
  },
  {
    id: '5',
    name: 'موبایل و گجت مارکت',
    websiteUrl: 'https://www.gadgetmarket.com',
    instagram: '@gadgetmarket',
    score: 4.6,
    category: 'gadgets',
    description: 'بهترین لوازم جانبی موبایل و گجت‌های هوشمند',
    address: 'مرکز خرید تکنولوژی، مشهد',
    phone: '+98 935 456 7890',
    email: 'support@gadgetmarket.com',
    tags: ['Tech', 'Mobile Accessories', 'Gadgets'],
    reviewCount: 125,
    ratingDistribution: {
      1: 5,
      2: 7,
      3: 20,
      4: 40,
      5: 53,
    },
  },
  {
    id: '6',
    name: 'عطرهای لوکس رویال',
    websiteUrl: 'https://www.royalperfumes.com',
    instagram: '@royalperfumes',
    score: 4.9,
    category: 'perfume',
    description: 'عطرهای خاص و لاکچری برای سلیقه‌های منحصر به فرد',
    address: 'خیابان عطر، تهران',
    phone: '+98 912 123 4567',
    email: 'info@royalperfumes.com',
    tags: ['Perfume', 'Luxury', 'Fragrance'],
    reviewCount: 275,
    ratingDistribution: {
      1: 1,
      2: 2,
      3: 8,
      4: 50,
      5: 214,
    },
  },
  {
    id: '7',
    name: 'خانه گیاه سبز',
    websiteUrl: 'https://www.greenplantshouse.com',
    instagram: '@greenplantshouse',
    score: 4.7,
    category: 'plants',
    description: 'فروش گیاهان آپارتمانی و تزئینی برای دکوراسیون منزل',
    address: 'گل‌فروشی مرکزی، تبریز',
    phone: '+98 935 678 9012',
    email: 'info@greenplantshouse.com',
    tags: ['Plants', 'Home Decor', 'Green Living'],
    reviewCount: 90,
    ratingDistribution: {
      1: 2,
      2: 4,
      3: 12,
      4: 35,
      5: 37,
    },
  },
  {
    id: '8',
    name: 'کتاب‌های دیجیتال ایرانی',
    websiteUrl: 'https://www.iraniandigitalbooks.com',
    instagram: '@iraniandigitalbooks',
    score: 4.8,
    category: 'digital_products',
    description: 'فروش کتاب‌های الکترونیکی و دوره‌های آنلاین',
    address: 'خیابان فرهنگ، اصفهان',
    phone: '+98 912 789 4567',
    email: 'support@iraniandigitalbooks.com',
    tags: ['Ebooks', 'Education', 'Digital'],
    reviewCount: 140,
    ratingDistribution: {
      1: 1,
      2: 3,
      3: 10,
      4: 50,
      5: 76,
    },
  },
  {
    id: '9',
    name: 'لباس‌های کودکانه نینی',
    websiteUrl: 'https://www.ninikidsfashion.com',
    instagram: '@ninikidsfashion',
    score: 4.9,
    category: 'baby_products',
    description: 'فروش انواع لباس‌های کودکانه و نوزادی با طراحی خاص',
    address: 'مرکز خرید کودک، تهران',
    phone: '+98 935 678 9012',
    email: 'info@ninikidsfashion.com',
    tags: ['Baby Clothes', 'Handmade', 'Fashion'],
    reviewCount: 230,
    ratingDistribution: {
      1: 1,
      2: 3,
      3: 8,
      4: 50,
      5: 168,
    },
  },
];
